In [1]:
import torch

In [13]:
#create some custom tesors
t0 = torch.tensor(1000)  #0-D tensor
t1 = torch.tensor([0,1,2,3])  #1-D tensor
t2 = torch.tensor([[4,5,6],[7,8,9]])  #2-D tensor

print(t0)
print(t1)
print(t2)

tensor(1000)
tensor([0, 1, 2, 3])
tensor([[4, 5, 6],
        [7, 8, 9]])


In [17]:
#set dattype for each tensor
a = torch.ones((2,3), dtype=torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


Tensor Data Types:
bool, int8, uint8, int16,
int32, int64, half, float,
double, bfloat

In [19]:
#tensor size
print(a.size())
print(a.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [21]:
#tensor dimension
print(a.ndimension())
print(a.ndim)

2
2


To change dimension to tensor,

    Tensor.view(nrows,ncols)

Flexibilities:
    
    In-place alterations
    Tensor copying
    Changing the shape of the tensor, such as altering the dimension of the tensor

GPU Support:

    Robust acceleation on CUDA-compatible NVIDIA GPUs
    Created on CPU by default; create on GPU using optional device argument
    Move from one device to another using the to() method