##### Broadcasting is a way to perform an operation between tensors that have similarities in their shapes.

This is an important operation in deep learning.

The common example is multiplying a tensor of learning weights by a batch of input tensors, applying the operation to each instance in the batch seperately and running a tensor of identical shape.

In [2]:
import torch

In [3]:
#simple operations
u = torch.tensor([2, 4])
v = torch.tensor([1, 4])
w = u * v
print(w)
print(w.shape)
print(w.ndim)

tensor([ 2, 16])
torch.Size([2])
1


##### Broadcasting Rules


    Each tensor must at least one dimension - no empty tensors
    
    Comparing the dimension sizes of the two tensors(from last to first):
        Each dimension must be equal
        One of the dimensions must be of size 1
        The dimension does not exist in one of the tensors
        
    Tensors of identical shape are trivially broadcastable

In [4]:
#broadcasting rules
a = torch.ones(4, 3, 2)
b = a * torch.rand(   3, 2) #3rd and 2nd dims identical to a, dim 1 absent
print(b)

tensor([[[0.2138, 0.7984],
         [0.3237, 0.3999],
         [0.2174, 0.7684]],

        [[0.2138, 0.7984],
         [0.3237, 0.3999],
         [0.2174, 0.7684]],

        [[0.2138, 0.7984],
         [0.3237, 0.3999],
         [0.2174, 0.7684]],

        [[0.2138, 0.7984],
         [0.3237, 0.3999],
         [0.2174, 0.7684]]])


In [5]:
c = a * torch.rand(   3, 1) #3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.0808, 0.0808],
         [0.6159, 0.6159],
         [0.8587, 0.8587]],

        [[0.0808, 0.0808],
         [0.6159, 0.6159],
         [0.8587, 0.8587]],

        [[0.0808, 0.0808],
         [0.6159, 0.6159],
         [0.8587, 0.8587]],

        [[0.0808, 0.0808],
         [0.6159, 0.6159],
         [0.8587, 0.8587]]])


In [6]:
d = a * torch.rand(   1, 2) #3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.3515, 0.5066],
         [0.3515, 0.5066],
         [0.3515, 0.5066]],

        [[0.3515, 0.5066],
         [0.3515, 0.5066],
         [0.3515, 0.5066]],

        [[0.3515, 0.5066],
         [0.3515, 0.5066],
         [0.3515, 0.5066]],

        [[0.3515, 0.5066],
         [0.3515, 0.5066],
         [0.3515, 0.5066]]])


In [7]:
#switch between ndarrays and PyTorch tensors
import numpy as np
numpy_arr = np.ones((2, 3))
print(numpy_arr)

pytorch_tensor = torch.from_numpy(numpy_arr)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
#reverse exaple of converting from PyTorch tensor to ndarray
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.5725, 0.9630, 0.2823],
        [0.2520, 0.1685, 0.4038]])
[[0.572482   0.9629582  0.2822786 ]
 [0.25201404 0.1684652  0.40381157]]


In [11]:
#using the same underlying memory
numpy_arr[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.572482    0.9629582   0.2822786 ]
 [ 0.25201404 17.          0.40381157]]
